# Configuration for Alacritty, the GPU-accelerated terminal emulator.

# Add theme locally
import = ["~/.config/alacritty/themes/themes/kanagawa_wave.toml"]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 1000
style = {shape = "underline", blinking = "always"}
vi_mode_style = "block"

[font]
size = 13.0
normal.family = "MesloLGS NF"
normal.style = "Regular"

[window]
decorations = "none"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
