
[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 1000
style = {shape = "underline", blinking = "always"}
vi_mode_style = "block"

[font]
size = 13.0
normal.family = "MesloLGS Nerd Font"

[window]
padding = {x = 0, y = 5}
decorations = "none"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[general]
# Configuration for Alacritty, the GPU-accelerated terminal emulator.

# Add theme locally
import = ["~/.config/alacritty/themes/themes/kanagawa_wave.toml"]
